apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Plants by was"
  description: "An example app"
  annotations:
    github.com/project-slug: ValberJunior/
    backstage.io/techdocs-ref: dir:.
   
spec:
  type: service
  lifecycle: development
  owner: "devops"