# Move to the .github/workflows folder
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml